pipeline {
    agent { label 'worker-node-1' }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/SuhasK97/Demo_Docker.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker compose build'
                echo 'Building on my new agent!'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}
