pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/SuhasK97/Demo_Docker.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}
